name: Release
on:
  release:
    types: [released, edited]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name that the major tag will point to"
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    environment:
      # Note: this environment is protected
      name: Release
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        id: update-major-tag
        uses: actions/publish-action@23f4c6f12633a2da8f44938b71fde9afec138fb4 # v0.4.0
        with:
          source-tag: ${{ env.TAG_NAME }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
